name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vayer-electric-frontend:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the Docker image
      run: docker push vayer-electric-frontend:$(git rev-parse --short "$GITHUB_SHA")
